services:
  mongodb:
    container_name: mongodb-wichat_es2a
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-wichat_es2a
    image: ghcr.io/arquisoft/wichat_es2a/authservice:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./users/authservice
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
      DEPLOY_HOST: ${DEPLOY_HOST:-localhost}
      WEBAPP_PORT: ${WEBAPP_PORT:-3000}
    restart: always

  userservice:
    container_name: userservice-wichat_es2a
    image: ghcr.io/arquisoft/wichat_es2a/userservice:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./users/userservice
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
      DEPLOY_HOST: ${DEPLOY_HOST:-localhost}
      WEBAPP_PORT: ${WEBAPP_PORT:-3000}
    restart: always

  groupservice:
    container_name: groupservice-wichat_es2a
    image: ghcr.io/arquisoft/wichat_es2a/groupservice:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./users/groupservice
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
      GATEWAY_URL: http://${DEPLOY_HOST:-localhost}:8000
    restart: always

  llmservice:
    container_name: llmservice-wichat_es2a
    image: ghcr.io/arquisoft/wichat_es2a/llmservice:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./llmservice
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - mongodb
    ports:
      - "8003:8003"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/llmdb
      DEPLOY_HOST: ${DEPLOY_HOST:-localhost}
      WEBAPP_PORT: ${WEBAPP_PORT:-3000}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      EMPATHY_API_KEY: ${EMPATHY_API_KEY}
    restart: always

  wikidata:
    container_name: wikidata-wichat_es2a
    image: ghcr.io/arquisoft/wichat_es2a/wikidata:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./wikidata
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/wikidatadb
      DEPLOY_HOST: ${DEPLOY_HOST:-localhost}
      WEBAPP_PORT: ${WEBAPP_PORT:-3000}
    restart: always

  gatewayservice:
    container_name: gatewayservice-wichat_es2a
    image: ghcr.io/arquisoft/wichat_es2a/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./gatewayservice
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - mongodb
      - userservice
      - authservice
      - llmservice
      - wikidata
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      LLM_SERVICE_URL: http://llmservice:8003
      WIKIDATA_SERVICE_URL: http://wikidata:3001
      GROUP_SERVICE_URL: http://groupservice:8004
      DEPLOY_HOST: ${DEPLOY_HOST:-localhost}
      WEBAPP_PORT: ${WEBAPP_PORT:-3000}
    restart: always

  apiservice:
    container_name: apiservice-wichat_es2a
    image: ghcr.io/arquisoft/wichat_es2a/apiservice:latest
    build: ./apiservice
    profiles: ["dev", "prod"]
    depends_on:
      - mongodb
      - authservice
      - userservice
      - wikidata
    ports:
      - "8008:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      WIKIDATA_SERVICE_URL: http://wikidata:3001

  webapp:
    container_name: webapp-wichat_es2a
    image: ghcr.io/arquisoft/wichat_es2a/webapp:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./webapp
      args:
        GATEWAY_URL: http://${DEPLOY_HOST:-localhost}:8000
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus-wichat_es2a
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-wichat_es2a
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus

volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
