ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
endif::arc42help[]



=== Technology decisions

For the development of the following project we have decided to use the following technologies.
Many of them have been based on the project template provided by the teachers, as we do not yet have sufficient depth of knowledge in these technologies (web development libraries and frameworks, docker...).

* *JavaScript*: Programming language mainly focused on web development on the client side, mainly used to provide interactivity to a web page.
* *React*: Open source JavaScript library used to create graphical user interfaces.
* *Node.js*: Execution environment using Javascript for server-side, rather than client-side.
* *Express*: Web framework for Node.js to simplify the implementation of web applications.
* *MongoDB*: NoSQL-like database, which stores data in a JSON-like format and favours application scalability and flexibility when it comes to handling unstructured data.
* *GitHub*: Web application used in software development that allows code to be written, stored, organised by version and collaborated on by different members of a team using Git.
* *Docker*: Tool that allows you to create, deploy and run applications in containers, testing that the application works in different environments.


=== Top-level decomposition of the system

An architecture using microservices has been chosen for this project, so that each module focuses on a specific task. Some of the modules will be the following:

* *User management service*: It will manage the creation of new users, their login, store their game history ...

* *Game service*: It will generate questions and possible answers from the chosen image.

* *Chat service*: It will use the LLM to help the user with hints to facilitate the game.

* *Wikidata connection service*: It will get the image and the necessary information from Wikidata.

* *Service to export user information*: It will allow access to user information stored in the system through an API.

* *Service to export the information of the questions*: It will allow access to the information of the questions through an API.


=== Decisions taken to achieve quality goals

|===

| Quality goal | Decision made

|*Usability*
|To ensure the usability of the application, an intuitive and simple interface will be designed so that the user has no doubts about what action to take at any moment.
In addition, a sufficiently legible font with an appropriate size and weight will be used.
Finally, the application will be made responsive to facilitate its use on different devices.

|*Maintainability*
|In order to facilitate the maintainability and expansion of the application, we will try to follow the good practices for software development acquired in other previous subjects of the degree.
An example of this will be some of the SOLID principles previously studied, such as the Single responsibility principle or the Open/closed principle.

|===
