apiVersion: v1
kind: ConfigMap
metadata:
  name: apiservice-config
  namespace: wichat-es2a
data:
  AUTH_SERVICE_URL: "http://authservice:8002"
  USER_SERVICE_URL: "http://userservice:8001"
  WIKIDATA_SERVICE_URL: "http://wikidata:3001"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  namespace: wichat-es2a
  labels:
    app: apiservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      automountServiceAccountToken: false
      containers:
      - name: apiservice
        image: wichat-apiservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8008
        env:
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: apiservice-config
              key: AUTH_SERVICE_URL
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: apiservice-config
              key: USER_SERVICE_URL
        - name: WIKIDATA_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: apiservice-config
              key: WIKIDATA_SERVICE_URL
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
  namespace: wichat-es2a
spec:
  selector:
    app: apiservice
  ports:
  - port: 8008
    targetPort: 8008
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice
  namespace: wichat-es2a
  labels:
    app: gatewayservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatewayservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gatewayservice
    spec:
      automountServiceAccountToken: false
      containers:
      - name: gatewayservice
        image: wichat-gatewayservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: gatewayservice
  namespace: wichat-es2a
spec:
  selector:
    app: gatewayservice
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer


