const answers = [{
    category: "Actores",
    actors : [
      "Leonardo DiCaprio", "Meryl Streep", "Tom Hanks", "Scarlett Johansson", "Denzel Washington",
      "Brad Pitt", "Angelina Jolie", "Robert De Niro", "Al Pacino", "Natalie Portman",
      "Johnny Depp", "Morgan Freeman", "Emma Stone", "Harrison Ford", "Nicole Kidman",
      "Matt Damon", "Cate Blanchett", "Keanu Reeves", "Joaquin Phoenix", "Anne Hathaway",
      "Jake Gyllenhaal", "Charlize Theron", "Tom Hardy", "Julia Roberts", "Chris Hemsworth",
      "Ryan Gosling", "Christian Bale", "Hugh Jackman", "Sandra Bullock", "Javier Bardem",
      "Ben Affleck", "Amy Adams", "Mark Ruffalo", "Tilda Swinton", "Edward Norton",
      "Viola Davis", "Jeff Bridges", "Jessica Chastain", "Samuel L. Jackson", "Michael Fassbender",
      "Cillian Murphy", "Robert Pattinson", "Chris Evans", "Zoe Saldana", "Salma Hayek",
      "Liam Neeson", "Ewan McGregor", "Saoirse Ronan", "Anya Taylor-Joy", "Margot Robbie",
      "Florence Pugh", "Benedict Cumberbatch", "Idris Elba", "Jared Leto", "Pedro Pascal",
      "Oscar Isaac", "Timothée Chalamet", "Daniel Radcliffe", "Emma Watson", "Rupert Grint",
      "Gal Gadot", "Henry Cavill", "Ezra Miller", "Jason Momoa", "Tom Holland",
      "Zendaya", "Paul Rudd", "Sebastian Stan", "Anthony Mackie", "Elizabeth Olsen",
      "Jeremy Renner", "Karen Gillan", "Chris Pratt", "Dave Bautista", "Josh Brolin",
      "Michael B. Jordan", "Halle Berry", "Winona Ryder", "Hugh Grant", "Helena Bonham Carter",
      "Gary Oldman", "Ian McKellen", "Patrick Stewart", "Dwayne Johnson", "Brendan Fraser",
      "John Travolta", "Gene Hackman", "Jack Nicholson", "Sophia Loren", "Jean Dujardin",
      "Maggie Smith", "Michelle Yeoh", "Ben Kingsley", "Chadwick Boseman", "Mahershala Ali",
      "John Boyega", "Lupita Nyong'o", "Daniel Kaluuya", "Rami Malek", "Rachel Weisz",
      "Eddie Redmayne", "Olivia Colman", "Regina King", "Jodie Comer", "Tommy Lee Jones",
      "Forest Whitaker", "Cate Blanchett", "Glenn Close", "Frances McDormand", "Anthony Hopkins",
      "Willem Dafoe", "Richard Gere", "Melissa McCarthy", "Mads Mikkelsen", "Taron Egerton",
      "Adam Driver", "Andrew Garfield", "Jamie Foxx", "Colin Farrell", "Rachel McAdams",
      "Michael Caine", "Emily Blunt", "Evangeline Lilly", "Rosamund Pike", "Bryce Dallas Howard",
      "Sam Rockwell", "Gina Rodriguez", "James McAvoy", "Felicity Jones", "Matt Smith",
      "Emma Mackey", "Austin Butler", "Dev Patel", "Sophie Turner", "Nicholas Hoult",
      "Millie Bobby Brown", "Finn Wolfhard", "Noah Centineo", "Joey King", "Sadie Sink",
      "Kaitlyn Dever", "Zoë Kravitz", "Jenna Ortega", "Bella Ramsey", "Hailee Steinfeld",
      "John Krasinski", "Emily Mortimer", "Adam Sandler", "Will Smith", "Woody Harrelson",
      "Kevin Hart", "Melissa Benoist", "Hugh Dancy", "Lucy Boynton", "Natalia Dyer",
      "Freddie Highmore", "Dafne Keen", "Florence Kasumba", "Tessa Thompson", "Gaten Matarazzo",
      "Caleb McLaughlin", "Maya Hawke", "Sadie Sink", "Ansel Elgort", "Lily Collins",
      "Jodie Foster", "Kristen Bell", "Sophia Lillis", "Jack Black", "Reese Witherspoon",
      "Sarah Paulson", "Jessica Lange", "Steve Buscemi", "Tim Roth", "Jesse Eisenberg",
      "Brie Larson", "Riz Ahmed", "Oscar Nunez", "Gael García Bernal", "Diego Luna",
      "Michael Peña", "Tenoch Huerta", "Ana de Armas", "Stephanie Beatriz", "Eiza González",
      "Luis Gerardo Méndez", "Kate del Castillo", "Salma Hayek", "Alfonso Herrera",
      "Yalitza Aparicio", "Mauricio Ochmann", "Sandra Echeverría", "Cecilia Suárez",
      "Manolo Cardona", "Miguel Ángel Silvestre", "Javier Cámara", "Blanca Suárez",
      "Mario Casas", "Macarena García", "Álvaro Morte", "Itziar Ituño", "Úrsula Corberó",
      "Jaime Lorente", "Najwa Nimri", "Miguel Herrán", "Paco León", "Carmen Machi"
    ]
  },
  {
    category : "Cantantes",
    singers : [
      "Freddie Mercury", "Beyoncé", "Elvis Presley", "Shakira", "Michael Jackson",
      "Adele", "Madonna", "Frank Sinatra", "Whitney Houston", "Ed Sheeran",
      "Lady Gaga", "David Bowie", "Rihanna", "Paul McCartney", "Elton John",
      "Bruno Mars", "Ariana Grande", "Bob Dylan", "Taylor Swift", "John Lennon",
      "Dua Lipa", "Mariah Carey", "Luis Miguel", "Celine Dion", "Prince",
      "Jennifer Lopez", "Billie Eilish", "Andrea Bocelli", "Maluma", "Eminem",
      "The Weeknd", "Amy Winehouse", "Harry Styles", "Rosalía", "Coldplay",
      "Shawn Mendes", "Bad Bunny", "Selena Quintanilla", "Britney Spears", "Ozzy Osbourne",
      "Travis Scott", "Post Malone", "Kanye West", "Drake", "Camila Cabello",
      "Doja Cat", "Olivia Rodrigo", "Justin Bieber", "Karol G", "J Balvin",
      "Anuel AA", "Daddy Yankee", "Rauw Alejandro", "Miley Cyrus", "Nicki Minaj",
      "Christina Aguilera", "Alicia Keys", "Bruno Mars", "Sam Smith", "Calvin Harris",
      "David Guetta", "Sia", "Katy Perry", "Charlie Puth", "Imagine Dragons",
      "OneRepublic", "Fonseca", "Pablo Alborán", "Melendi", "Ricardo Arjona",
      "Alejandro Sanz", "Luis Fonsi", "Chayanne", "Enrique Iglesias", "Marc Anthony",
      "Juan Gabriel", "José José", "Vicente Fernández", "Gloria Trevi", "Natalie Imbruglia",
      "Fito Páez", "Julieta Venegas", "Zoé", "Café Tacvba", "Maná",
      "Caifanes", "Hombres G", "El Tri", "Los Fabulosos Cadillacs", "Molotov",
      "Babasónicos", "Bunbury", "Andrés Calamaro", "Nirvana", "Linkin Park"
    ]
  },
  {
    category : "Arte",
    art : [
      "La Gioconda", "La última cena", "La persistencia de la memoria", "Las meninas", "La noche estrellada",
      "El nacimiento de Venus", "La creación de Adán", "El grito", "Guernica", "El jardín de las delicias",
      "La joven de la perla", "El beso", "Las dos Fridas", "La rendición de Breda", "El caballero de la mano en el pecho",
      "Saturno devorando a su hijo", "El juicio final", "Impresión, sol naciente", "El almuerzo sobre la hierba",
      "La libertad guiando al pueblo", "Los girasoles", "Baco", "El matrimonio Arnolfini", "Cristo muerto",
      "Las espigadoras", "La balsa de la Medusa", "La ronda de noche", "El descendimiento de la cruz",
      "La escuela de Atenas", "Mujer con sombrero", "Los fusilamientos del 3 de mayo", "La Virgen del canciller Rolin",
      "Retrato de Giovanni Arnolfini y su esposa", "San Juan Bautista", "La tentación de San Antonio",
      "Retrato de un hombre con turbante rojo", "Las tres gracias", "El nacimiento de Venus (Bouguereau)",
      "El entierro del conde de Orgaz", "El lavatorio", "Marte desarmado por Venus y las Gracias",
      "Venus de Urbino", "Judith decapitando a Holofernes", "La Anunciación", "La Primavera", "El carro de heno",
      "Retrato de Dorian Gray", "El rapto de Europa", "Los desposorios de la Virgen", "La dama del armiño",
      "El martirio de San Bartolomé", "El niño azul", "Vista de Delft", "La encajera", "Las bodas de Caná",
      "La tormenta en el mar de Galilea", "Autorretrato con oreja vendada", "El almuerzo de los remeros",
      "El columpio", "Bailarina basculando", "La gitana dormida", "La maja desnuda", "Los jugadores de cartas",
      "Los paraguas", "San Jerónimo escribiendo", "El hijo del hombre", "Las lavanderas",
      "Retrato de la madre del artista", "La Venus del espejo", "El caminante sobre el mar de nubes",
      "El baño turco", "Mujer ante el espejo", "Cristo crucificado", "Leda y el cisne", "Retrato de la infanta Margarita",
      "El violinista azul", "Mujer con una sombrilla", "Autorretrato con mono", "La muerte de Marat",
      "Madonna del Prato", "La Melancolía", "El rapto de las hijas de Leucipo", "La Asunción de la Virgen",
      "El rapto de Proserpina", "San Sebastián", "El rapto de las Sabinas", "Baco y Ariadna", "El astrónomo",
      "El jardinero", "El portador de flores", "La Virgen de las Rocas", "El baño de Diana", "La batalla de San Romano"
    ]
  },
  {
    category : "Lugares",
    places : [
      "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia",
      "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin",
      "Bélgica", "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil",
      "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar",
      "Chad", "Chile", "China", "Chipre", "Colombia", "Comoras", "Congo", "Corea del Norte", "Corea del Sur", "Costa de Marfil",
      "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos",
      "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Esuatini", "Etiopía", "Filipinas",
      "Finlandia", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guinea",
      "Guinea-Bisáu", "Guinea Ecuatorial", "Guyana", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán",
      "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón", "Jordania",
      "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia",
      "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí",
      "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro",
      "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán",
      "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal",
      "Reino Unido", "República Checa", "República Dominicana", "Ruanda", "Rumania", "Rusia", "Samoa", "San Cristóbal y Nieves",
      "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles",
      "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia",
      "Suiza", "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago",
      "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu",
      "Vaticano", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue"
    ]
  },
  {
    category : "Películas",
    movies : [
      "El Padrino", "El Padrino II", "El Padrino III", "Titanic", "Forrest Gump", "El caballero oscuro",
      "Interestelar", "Inception", "Matrix", "Pulp Fiction", "El Señor de los Anillos: La Comunidad del Anillo",
      "El Señor de los Anillos: Las Dos Torres", "El Señor de los Anillos: El Retorno del Rey", "Gladiador",
      "Braveheart", "Salvar al Soldado Ryan", "La lista de Schindler", "Cadena Perpetua", "El gran dictador",
      "Ciudad de Dios", "La vida es bella", "El laberinto del fauno", "Coco", "Ratatouille", "Toy Story",
      "Toy Story 2", "Toy Story 3", "Toy Story 4", "Buscando a Nemo", "Buscando a Dory", "Up", "Inside Out",
      "Soul", "WALL·E", "Los Increíbles", "Los Increíbles 2", "Cars", "Cars 2", "Cars 3", "Frozen", "Frozen II",
      "Encanto", "Moana", "El Rey León", "Aladdin", "Hércules", "Tarzán", "Mulan", "La Bella y la Bestia",
      "Blancanieves y los siete enanitos", "Cenicienta", "Peter Pan", "El Libro de la Selva", "Pinocho",
      "Alicia en el país de las maravillas", "Dumbo", "Bambi", "101 dálmatas", "La dama y el vagabundo",
      "La sirenita", "Pocahontas", "Los aristogatos", "Robin Hood", "Zootopia", "Luca", "Red", "Elemental",
      "Los Minions", "Mi villano favorito", "Mi villano favorito 2", "Mi villano favorito 3", "Shrek",
      "Shrek 2", "Shrek Tercero", "Shrek: Felices para siempre", "Kung Fu Panda", "Kung Fu Panda 2",
      "Kung Fu Panda 3", "Madagascar", "Madagascar 2", "Madagascar 3", "Cómo entrenar a tu dragón",
      "Cómo entrenar a tu dragón 2", "Cómo entrenar a tu dragón 3", "Spider-Man", "Spider-Man 2",
      "Spider-Man 3", "El sorprendente Hombre Araña", "El sorprendente Hombre Araña 2", "Spider-Man: Homecoming",
      "Spider-Man: Lejos de casa", "Spider-Man: Sin camino a casa", "Spider-Man: Un nuevo universo",
      "Spider-Man: A través del Spider-Verso", "Avengers", "Avengers: La era de Ultrón", "Avengers: Infinity War",
      "Avengers: Endgame", "Iron Man", "Iron Man 2", "Iron Man 3", "Thor", "Thor: El mundo oscuro",
      "Thor: Ragnarok", "Thor: Amor y Trueno", "Capitán América: El primer vengador", "Capitán América: El Soldado de Invierno",
      "Capitán América: Civil War", "Guardianes de la Galaxia", "Guardianes de la Galaxia Vol. 2",
      "Guardianes de la Galaxia Vol. 3", "Doctor Strange", "Doctor Strange en el multiverso de la locura",
      "Black Panther", "Black Panther: Wakanda Forever", "Ant-Man", "Ant-Man y la Avispa", "Ant-Man y la Avispa: Quantumania",
      "Deadpool", "Deadpool 2", "Logan", "X-Men", "X-Men 2", "X-Men: La batalla final", "X-Men: Primera Generación",
      "X-Men: Días del futuro pasado", "X-Men: Apocalipsis", "X-Men: Dark Phoenix", "The Batman",
      "Joker", "El Hombre de Acero", "Batman vs Superman", "Escuadrón Suicida", "La Liga de la Justicia",
      "Wonder Woman", "Wonder Woman 1984", "Aquaman", "The Flash", "Black Adam", "The Suicide Squad",
      "Harry Potter y la piedra filosofal", "Harry Potter y la cámara secreta", "Harry Potter y el prisionero de Azkaban",
      "Harry Potter y el cáliz de fuego", "Harry Potter y la Orden del Fénix", "Harry Potter y el misterio del príncipe",
      "Harry Potter y las Reliquias de la Muerte – Parte 1", "Harry Potter y las Reliquias de la Muerte – Parte 2",
      "Animales fantásticos y dónde encontrarlos", "Animales fantásticos: Los crímenes de Grindelwald",
      "Animales fantásticos: Los secretos de Dumbledore", "Los juegos del hambre", "Los juegos del hambre: En llamas",
      "Los juegos del hambre: Sinsajo Parte 1", "Los juegos del hambre: Sinsajo Parte 2", "Duna",
      "Duna: Parte Dos", "El resplandor", "IT", "IT: Capítulo 2", "Expediente Warren: El Conjuro",
      "Expediente Warren: El Conjuro 2", "El Conjuro 3: El diablo me obligó a hacerlo", "Annabelle",
      "Annabelle 2: La creación", "Annabelle vuelve a casa", "La Monja", "La Monja 2", "Saw",
      "Saw II", "Saw III", "Saw IV", "Saw V", "Saw VI", "Jigsaw", "Spiral: El juego del miedo continúa",
      "Scream", "Scream 2", "Scream 3", "Scream 4", "Scream 5", "Scream 6", "El exorcista",
      "El exorcista: Creyentes", "Psicosis", "Halloween", "Halloween Kills", "Halloween Ends",
      "Viernes 13", "Pesadilla en Elm Street", "Destino Final", "Destino Final 2", "Destino Final 3",
      "Destino Final 4", "Destino Final 5", "La matanza de Texas", "La mosca", "El hombre invisible",
      "El silencio de los inocentes", "Seven", "Zodiac", "El club de la pelea", "El origen del planeta de los simios",
      "El amanecer del planeta de los simios", "La guerra del planeta de los simios", "Oppenheimer",
      "Barbie", "Everything Everywhere All At Once"
    ]
  }
];
    

  
  