module.exports = [{
    category: "Actores",
    answers : [
      "Leonardo DiCaprio", "Meryl Streep", "Tom Hanks", "Scarlett Johansson", "Denzel Washington",
      "Brad Pitt", "Angelina Jolie", "Robert De Niro", "Al Pacino", "Natalie Portman",
      "Johnny Depp", "Morgan Freeman", "Emma Stone", "Harrison Ford", "Nicole Kidman",
      "Matt Damon", "Cate Blanchett", "Keanu Reeves", "Joaquin Phoenix", "Anne Hathaway",
      "Jake Gyllenhaal", "Charlize Theron", "Tom Hardy", "Julia Roberts", "Chris Hemsworth",
      "Ryan Gosling", "Christian Bale", "Hugh Jackman", "Sandra Bullock", "Javier Bardem",
      "Ben Affleck", "Amy Adams", "Mark Ruffalo", "Tilda Swinton", "Edward Norton",
      "Viola Davis", "Jeff Bridges", "Jessica Chastain", "Samuel L. Jackson", "Michael Fassbender",
      "Cillian Murphy", "Robert Pattinson", "Chris Evans", "Zoe Saldana", "Salma Hayek",
      "Liam Neeson", "Ewan McGregor", "Saoirse Ronan", "Anya Taylor-Joy", "Margot Robbie",
      "Florence Pugh", "Benedict Cumberbatch", "Idris Elba", "Jared Leto", "Pedro Pascal",
      "Oscar Isaac", "Timothée Chalamet", "Daniel Radcliffe", "Emma Watson", "Rupert Grint",
      "Gal Gadot", "Henry Cavill", "Ezra Miller", "Jason Momoa", "Tom Holland",
      "Zendaya", "Paul Rudd", "Sebastian Stan", "Anthony Mackie", "Elizabeth Olsen",
      "Jeremy Renner", "Karen Gillan", "Chris Pratt", "Dave Bautista", "Josh Brolin",
      "Michael B. Jordan", "Halle Berry", "Winona Ryder", "Hugh Grant", "Helena Bonham Carter",
      "Gary Oldman", "Ian McKellen", "Patrick Stewart", "Dwayne Johnson", "Brendan Fraser",
      "John Travolta", "Gene Hackman", "Jack Nicholson", "Sophia Loren", "Jean Dujardin",
      "Maggie Smith", "Michelle Yeoh", "Ben Kingsley", "Chadwick Boseman", "Mahershala Ali",
      "John Boyega", "Lupita Nyong'o", "Daniel Kaluuya", "Rami Malek", "Rachel Weisz",
      "Eddie Redmayne", "Olivia Colman", "Regina King", "Jodie Comer", "Tommy Lee Jones",
      "Forest Whitaker", "Cate Blanchett", "Glenn Close", "Frances McDormand", "Anthony Hopkins",
      "Willem Dafoe", "Richard Gere", "Melissa McCarthy", "Mads Mikkelsen", "Taron Egerton",
      "Adam Driver", "Andrew Garfield", "Jamie Foxx", "Colin Farrell", "Rachel McAdams",
      "Michael Caine", "Emily Blunt", "Evangeline Lilly", "Rosamund Pike", "Bryce Dallas Howard",
      "Sam Rockwell", "Gina Rodriguez", "James McAvoy", "Felicity Jones", "Matt Smith",
      "Emma Mackey", "Austin Butler", "Dev Patel", "Sophie Turner", "Nicholas Hoult",
      "Millie Bobby Brown", "Finn Wolfhard", "Noah Centineo", "Joey King", "Sadie Sink",
      "Kaitlyn Dever", "Zoë Kravitz", "Jenna Ortega", "Bella Ramsey", "Hailee Steinfeld",
      "John Krasinski", "Emily Mortimer", "Adam Sandler", "Will Smith", "Woody Harrelson",
      "Kevin Hart", "Melissa Benoist", "Hugh Dancy", "Lucy Boynton", "Natalia Dyer",
      "Freddie Highmore", "Dafne Keen", "Florence Kasumba", "Tessa Thompson", "Gaten Matarazzo",
      "Caleb McLaughlin", "Maya Hawke", "Sadie Sink", "Ansel Elgort", "Lily Collins",
      "Jodie Foster", "Kristen Bell", "Sophia Lillis", "Jack Black", "Reese Witherspoon",
      "Sarah Paulson", "Jessica Lange", "Steve Buscemi", "Tim Roth", "Jesse Eisenberg",
      "Brie Larson", "Riz Ahmed", "Oscar Nunez", "Gael García Bernal", "Diego Luna",
      "Michael Peña", "Tenoch Huerta", "Ana de Armas", "Stephanie Beatriz", "Eiza González",
      "Luis Gerardo Méndez", "Kate del Castillo", "Salma Hayek", "Alfonso Herrera",
      "Yalitza Aparicio", "Mauricio Ochmann", "Sandra Echeverría", "Cecilia Suárez",
      "Manolo Cardona", "Miguel Ángel Silvestre", "Javier Cámara", "Blanca Suárez",
      "Mario Casas", "Macarena García", "Álvaro Morte", "Itziar Ituño", "Úrsula Corberó",
      "Jaime Lorente", "Najwa Nimri", "Miguel Herrán", "Paco León", "Carmen Machi"
    ]
  },
  {
    category : "Cantantes",
    answers : [
      "Freddie Mercury", "Beyoncé", "Elvis Presley", "Shakira", "Michael Jackson",
      "Adele", "Madonna", "Frank Sinatra", "Whitney Houston", "Ed Sheeran",
      "Lady Gaga", "David Bowie", "Rihanna", "Paul McCartney", "Elton John",
      "Bruno Mars", "Ariana Grande", "Bob Dylan", "Taylor Swift", "John Lennon",
      "Dua Lipa", "Mariah Carey", "Luis Miguel", "Celine Dion", "Prince",
      "Jennifer Lopez", "Billie Eilish", "Andrea Bocelli", "Maluma", "Eminem",
      "The Weeknd", "Amy Winehouse", "Harry Styles", "Rosalía", "Coldplay",
      "Shawn Mendes", "Bad Bunny", "Selena Quintanilla", "Britney Spears", "Ozzy Osbourne",
      "Travis Scott", "Post Malone", "Kanye West", "Drake", "Camila Cabello",
      "Doja Cat", "Olivia Rodrigo", "Justin Bieber", "Karol G", "J Balvin",
      "Anuel AA", "Daddy Yankee", "Rauw Alejandro", "Miley Cyrus", "Nicki Minaj",
      "Christina Aguilera", "Alicia Keys", "Bruno Mars", "Sam Smith", "Calvin Harris",
      "David Guetta", "Sia", "Katy Perry", "Charlie Puth", "Imagine Dragons",
      "OneRepublic", "Fonseca", "Pablo Alborán", "Melendi", "Ricardo Arjona",
      "Alejandro Sanz", "Luis Fonsi", "Chayanne", "Enrique Iglesias", "Marc Anthony",
      "Juan Gabriel", "José José", "Vicente Fernández", "Gloria Trevi", "Natalie Imbruglia",
      "Fito Páez", "Julieta Venegas", "Zoé", "Café Tacvba", "Maná",
      "Caifanes", "Hombres G", "El Tri", "Los Fabulosos Cadillacs", "Molotov",
      "Babasónicos", "Bunbury", "Andrés Calamaro", "Nirvana", "Linkin Park"
    ]
  },
  {
    category : "Arte",
    answers : [
      "La Gioconda", "La última cena", "La persistencia de la memoria", "Las meninas", "La noche estrellada",
      "El nacimiento de Venus", "La creación de Adán", "El grito", "Guernica", "El jardín de las delicias",
      "La joven de la perla", "El beso", "Las dos Fridas", "La rendición de Breda", "El caballero de la mano en el pecho",
      "Saturno devorando a su hijo", "El juicio final", "Impresión, sol naciente", "El almuerzo sobre la hierba",
      "La libertad guiando al pueblo", "Los girasoles", "Baco", "El matrimonio Arnolfini", "Cristo muerto",
      "Las espigadoras", "La balsa de la Medusa", "La ronda de noche", "El descendimiento de la cruz",
      "La escuela de Atenas", "Mujer con sombrero", "Los fusilamientos del 3 de mayo", "La Virgen del canciller Rolin",
      "Retrato de Giovanni Arnolfini y su esposa", "San Juan Bautista", "La tentación de San Antonio",
      "Retrato de un hombre con turbante rojo", "Las tres gracias", "El nacimiento de Venus (Bouguereau)",
      "El entierro del conde de Orgaz", "El lavatorio", "Marte desarmado por Venus y las Gracias",
      "Venus de Urbino", "Judith decapitando a Holofernes", "La Anunciación", "La Primavera", "El carro de heno",
      "Retrato de Dorian Gray", "El rapto de Europa", "Los desposorios de la Virgen", "La dama del armiño",
      "El martirio de San Bartolomé", "El niño azul", "Vista de Delft", "La encajera", "Las bodas de Caná",
      "La tormenta en el mar de Galilea", "Autorretrato con oreja vendada", "El almuerzo de los remeros",
      "El columpio", "Bailarina basculando", "La gitana dormida", "La maja desnuda", "Los jugadores de cartas",
      "Los paraguas", "San Jerónimo escribiendo", "El hijo del hombre", "Las lavanderas",
      "Retrato de la madre del artista", "La Venus del espejo", "El caminante sobre el mar de nubes",
      "El baño turco", "Mujer ante el espejo", "Cristo crucificado", "Leda y el cisne", "Retrato de la infanta Margarita",
      "El violinista azul", "Mujer con una sombrilla", "Autorretrato con mono", "La muerte de Marat",
      "Madonna del Prato", "La Melancolía", "El rapto de las hijas de Leucipo", "La Asunción de la Virgen",
      "El rapto de Proserpina", "San Sebastián", "El rapto de las Sabinas", "Baco y Ariadna", "El astrónomo",
      "El jardinero", "El portador de flores", "La Virgen de las Rocas", "El baño de Diana", "La batalla de San Romano"
    ]
  },
  {
    category : "Lugares",
    answers : [
      "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia",
      "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin",
      "Bélgica", "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil",
      "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar",
      "Chad", "Chile", "China", "Chipre", "Colombia", "Comoras", "Congo", "Corea del Norte", "Corea del Sur", "Costa de Marfil",
      "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos",
      "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Esuatini", "Etiopía", "Filipinas",
      "Finlandia", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guinea",
      "Guinea-Bisáu", "Guinea Ecuatorial", "Guyana", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán",
      "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón", "Jordania",
      "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia",
      "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí",
      "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro",
      "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán",
      "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal",
      "Reino Unido", "República Checa", "República Dominicana", "Ruanda", "Rumania", "Rusia", "Samoa", "San Cristóbal y Nieves",
      "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles",
      "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia",
      "Suiza", "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago",
      "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu",
      "Vaticano", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue"
    ]
  },
  {
    category: "Pintores",
    answers: [
      "Leonardo da Vinci", "Michelangelo Buonarroti", "Raphael Sanzio", "Tiziano Vecellio", "Sandro Botticelli", "Albrecht Dürer", "Caravaggio (Michelangelo Merisi)", "Rembrandt van Rijn", "Johannes Vermeer", "Diego Velázquez",
      "Francisco de Goya", "Édouard Manet", "Claude Monet", "Edgar Degas", "Pierre-Auguste Renoir", "Paul Cézanne", "Vincent van Gogh", "Paul Gauguin", "Henri Matisse", "Pablo Picasso",
      "Georges Braque", "Salvador Dalí", "René Magritte", "Joan Miró", "Marc Chagall", "Wassily Kandinsky", "Piet Mondrian", "Jackson Pollock", "Mark Rothko", "Andy Warhol",
      "Roy Lichtenstein", "Frida Kahlo", "Diego Rivera", "Georgia O'Keeffe", "Edward Hopper", "Grant Wood", "Gustav Klimt", "Egon Schiele", "Amedeo Modigliani", "Francis Bacon",
      "Lucian Freud", "David Hockney", "Jean-Michel Basquiat", "Keith Haring", "Cy Twombly", "Anselm Kiefer", "Jeff Koons", "Yayoi Kusama", "Zdzisław Beksiński", "Paul Klee",
      "Fernand Léger", "Robert Delaunay", "Sonia Delaunay", "Kazimir Malevich", "El Lissitzky", "David Alfaro Siqueiros", "José Clemente Orozco", "Thomas Cole", "Frederic Edwin Church", "Asher B. Durand",
      "Winslow Homer", "John Singer Sargent", "James McNeill Whistler", "Gustave Courbet", "Jean-François Millet", "Honoré Daumier", "Camille Pissarro", "Alfred Sisley", "Berthe Morisot", "Mary Cassatt",
      "Childe Hassam", "Maurice Utrillo", "Raoul Dufy", "André Derain", "Georges Seurat", "Paul Signac", "Henri Rousseau", "Maurice de Vlaminck", "André Lhote", "Giorgio de Chirico",
      "Max Ernst", "Francis Picabia", "Roberto Matta", "Lucio Fontana", "Antonio Berni", "Joaquín Torres García", "Emilio Pettoruti", "Osvaldo Borda", "Fernando Botero", "Armando Reverón",
      "Carmen Herrera", "Jesús Rafael Soto", "Carlos Cruz-Diez", "Antonio López García", "Joan Mitchell", "Helen Frankenthaler", "Grace Hartigan", "Willem de Kooning", "Franz Kline", "Robert Motherwell",
      "Clyfford Still", "Philip Guston", "Richard Diebenkorn", "David Salle", "Julian Schnabel", "Eric Fischl", "Jasper Johns", "Robert Rauschenberg", "Ellsworth Kelly", "Agnes Martin",
      "Sol LeWitt", "Donald Sultan", "R.B. Kitaj", "Alice Neel", "Fairfield Porter", "Wayne Thiebaud", "Robert Indiana", "Tom Wesselmann", "Victor Vasarely", "Bridget Riley",
      "Julian Opie", "Damien Hirst", "Takashi Murakami", "Yoshitomo Nara", "Kohei Nawa", "Shinique Smith", "Mickalene Thomas", "Cecily Brown", "Njideka Akunyili Crosby", "Lynette Yiadom-Boakye",
      "Elizabeth Peyton", "Tracey Emin", "Marlene Dumas", "Gerhard Richter", "Sigmar Polke", "Markus Lüpertz", "Georg Baselitz", "Neo Rauch", "Jörg Immendorff", "Rainer Fetting",
      "Martin Kippenberger", "Sean Scully", "Mary Heilmann", "Amy Sillman", "Kerry James Marshall", "Fernando Zóbel", "Rufino Tamayo", "Joaquín Sorolla", "Miguel Covarrubias", "Cándido López",
      "Juan Gris", "Giorgio Morandi", "Oskar Schlemmer", "Otto Dix", "Franz von Stuck", "John William Waterhouse", "Edward Burne-Jones", "Frederic Leighton", "Lawrence Alma-Tadema", "Jean-Léon Gérôme",
      "Henri de Toulouse-Lautrec", "Eugène Atget", "Anders Zorn", "Lars Lerin", "Odd Nerdrum", "Magdalena Abakanowicz", "Bruno Liljefors", "Vilhelm Hammershøi"
    ]
  }  
];
    

  
  